language: csharp
os:
  - linux
  - osx
mono:
  - latest
solution: SpiroNet.mono.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gtk-sharp2 ; fi
  - mono .nuget/nuget.exe restore SpiroNet.mono.sln
script:
  - xbuild /p:Configuration=Release SpiroNet.mono.sln
