language: csharp
os: linux
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono:
  - latest
dotnet: 1.0.1
script:
  - ./build.sh --target "Travis" --platform "Mono" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/214f3a64f2683a8a948a
    on_success: change
    on_failure: always
    on_start: never
