image: Visual Studio 2015
platform:
- Any CPU
configuration:
- Release
environment:
  NUGET_API_KEY:
    secure: iSkm19DNdKOLxxCvHiaKikWXy25ZMwGBKpv+EgEprliGl0qX5HtKohLmwJsLnx5O
  NUGET_API_URL: https://www.nuget.org/api/v2/package
  MYGET_API_KEY:
    secure: xhYvrWYPHdNI+mQD+f4Zu3baL7fqW+nO/hYXJdN070Lej8wpa6gfrLi1NGtnQlAs
  MYGET_API_URL: https://www.myget.org/F/spironet-nightly/api/v2/package
before_build:
- cmd: git submodule update --init
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform "$env:platform" -Configuration "$env:configuration"
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/3211907a32bb8b42a441
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: artifacts\test-results\*.xml
  - path: artifacts\nuget\*.nupkg
  - path: artifacts\zip\*.zip
